export const CARAVANAS_STORAGE_KEY = 'CARAVANAS';
export const COMPANY_STORAGE_KEY = 'COMPANY';
export const MOVEMENTS_STORAGE_KEY = 'MOVEMENT';
export const SETTINGS_STORAGE_KEY = 'SETTINGS';
export const STORAGE_TYPE = {
  ARRAY: 'ARRAY',
  OBJECT: 'OBJECT',
};

