export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const SETTINGS_REQUEST = 'SETTINGS_SET_REQUEST';
export const SETTINGS_RECEIVED = 'SETTINGS_SET_RECEIVED';
export const SETTINGS_REJECT = 'SETTINGS_SET_REJECT';
