export const COMPANY_CREATE_RECEIVED = 'COMPANY_CREATE_RECEIVED';
export const COMPANY_CREATE_REJECT = 'COMPANY_CREATE_REJECT';
export const COMPANY_CREATE_REQUEST = 'COMPANY_CREATE_REQUEST';
export const COMPANY_FETCH_RECEIVED = 'COMPANY_FETCH_RECEIVED';
export const COMPANY_FETCH_REJECT = 'COMPANY_FETCH_REJECT';
export const COMPANY_FETCH_REQUEST = 'COMPANY_FETCH_REQUEST';

export const SETTINGS_RECEIVED = 'SETTINGS_SET_RECEIVED';
export const SETTINGS_REJECT = 'SETTINGS_SET_REJECT';
export const SETTINGS_REQUEST = 'SETTINGS_SET_REQUEST';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
