// CARAVANA
export const CARAVANA_SAVE_RECEIVED = 'CARAVANA_SAVE_RECEIVED';
export const CARAVANA_SAVE_REJECT = 'CARAVANA_SAVE_REJECT';
export const CARAVANA_SAVE_REQUEST = 'CARAVANA_SAVE_REQUEST';
export const CARAVANA_DELETE_RECEIVED = 'CARAVANA_DELETE_RECEIVED';
export const CARAVANA_DELETE_REJECT = 'CARAVANA_DELETE_REJECT';
export const CARAVANA_DELETE_REQUEST = 'CARAVANA_DELETE_REQUEST';
export const CARAVANA_LIST_SET_MODE = 'CARAVANA_LIST_SET_MODE';
export const CARAVANA_FETCH_RECEIVED = 'CARAVANA_FETCH_RECEIVED';
export const CARAVANA_FETCH_REJECT = 'CARAVANA_FETCH_REJECT';
export const CARAVANA_FETCH_REQUEST = 'CARAVANA_FETCH_REQUEST';

// COMPANY
export const COMPANY_DELETE_RECEIVED = 'COMPANY_DELETE_RECEIVED';
export const COMPANY_DELETE_REJECT = 'COMPANY_DELETE_REJECT';
export const COMPANY_DELETE_REQUEST = 'COMPANY_DELETE_REQUEST';
export const COMPANY_FETCH_RECEIVED = 'COMPANY_FETCH_RECEIVED';
export const COMPANY_FETCH_REJECT = 'COMPANY_FETCH_REJECT';
export const COMPANY_FETCH_REQUEST = 'COMPANY_FETCH_REQUEST';
export const COMPANY_LIST_SET_MODE = 'COMPANY_LIST_SET_MODE ';
export const COMPANY_SAVE_RECEIVED = 'COMPANY_SAVE_RECEIVED';
export const COMPANY_SAVE_REJECT = 'COMPANY_SAVE_REJECT';
export const COMPANY_SAVE_REQUEST = 'COMPANY_SAVE_REQUEST';

// SETTINGS
export const SETTINGS_FETCH_RECEIVED = 'SETTINGS__FETCH__RECEIVED';
export const SETTINGS_FETCH_REJECT = 'SETTINGS__FETCH__REJECT';
export const SETTINGS_FETCH_REQUEST = 'SETTINGS__FETCH__REQUEST';
export const SETTINGS_SAVE_RECEIVED = 'SETTINGS_SAVE_RECEIVED';
export const SETTINGS_SAVE_REJECT = 'SETTINGS_SAVE_REJECT';
export const SETTINGS_SAVE_REQUEST = 'SETTINGS_SAVE_REQUEST';

// SIDEBAR
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';
